version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lriwnl
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: teste

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 